### ISSUE TITLE
Practica de Reconocimiento de imágenes

### ISSUE THREAD

**Issue by AxayacatlS** [SistemasTecTlaxiaco/reconocimiento-de-imagenes-con-ra-equipoaxayacatl#2]
[Practica de reconocimiento.pdf](https://github.com/SistemasTecTlaxiaco/reconocimiento-de-imagenes-con-ra-equipoaxayacatl/files/6508223/Practica.de.reconocimiento.pdf)

**Comment by Francisco536** [comment]
buen trabajo
Calificación: 20

**Comment by josealfredo79** [comment]
Bien hecho y revisado
